### ISSUE TITLE
Mention Cakebrew

### ISSUE THREAD

**Issue by artginzburg** [GetOpenStore/getopenstore.github.io#3]
The website should probably mention that Overt is a modern and more powerful alternative to [Cakebrew](https://www.cakebrew.com), just so that the Cakebrew users get to hear about Overt

**Comment by ThatsJustCheesy** [comment]
https://github.com/GetOvert/getovert.github.io/commit/423bf49b1ce67e630af8fd0b0f997d2e95c90999

https://getovert.app/about/#how-is-it-different-from-cakebrew
